### ISSUE TITLE
parse "true" as boolean if variable is defined as boolean

### ISSUE THREAD

**Issue by biskit** [evermeer/EVReflection#102]
other frameworks seem to take json `{"b":true} and {"b":"true"}` as same as long as class is defined as

```
class foo {
   var b: Bool
}
```

**Comment by evermeer** [comment]
Strange how I could have missed this one and it's only reported now...

I just pushed version 2.38.2 to GitHub and CocoaPods with a fix for this.
The values 'true', 'yes' and 1 (case insensitive) will be treaded as true if the target is a boolean. All other values will be false.

You can find the unit test for this issue here:
https://github.com/evermeer/EVReflection/blob/b430481b8e9d3764fd1879d1ac3103caf5cee1aa/EVReflection/EVReflectionTests/EVReflectionIssue102.swift#L26-L26
