### ISSUE TITLE
Using EVReflection in an App Extension

### ISSUE THREAD

**Issue by realenginerd** [evermeer/EVReflection#104]
I'm using EVReflection to serialize data for storage in an App Extension. However, linking to EVReflection causes Xcode (7.3) to emit this warning message:

> ld: warning: linking against a dylib which is not safe for use in application extensions: /Users/.../Build/Products/Debug-iphoneos/EVReflection.framework/EVReflection

According to [Apple](https://developer.apple.com/library/prerelease/content/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html), "the App Store rejects any app extension that links to such frameworks or that otherwise uses unavailable APIs". In addition, they say that "to configure an app extension target to use an embedded framework, set the target’s “Require Only App-Extension-Safe API” build setting to Yes". 

I noticed that EVReflection's "Require Only App-Extension-Safe API" build setting is set to 'No', but changing it to 'Yes' does not affect the build process; the framework compiles successfully. That said, what would be the best course of action now: fork EVReflection or create a pull request?

**Comment by evermeer** [comment]
Well, If it does not reflect anything else, then a pull request would be welcome. Let me do a quick search to see if there could be any side effects.

**Comment by evermeer** [comment]
Ah,

The documentation is quite clear:
https://developer.apple.com/library/prerelease/content/documentation/General/Conceptual/ExtensibilityPG/ExtensionOverview.html#//apple_ref/doc/uid/TP40014214-CH2-SW6

I think there would be nothing against adding this option. Could you please do a pull request for this? That would be great because I do not have any extension code where I could test this with.

**Comment by realenginerd** [comment]
Understood. PR incoming...

**Comment by evermeer** [comment]
This has now been released as version 2.39.0
