### ISSUE TITLE
Inconsistent conversion NSNumber/String

### ISSUE THREAD

**Issue by kukudas** [evermeer/EVReflection#11]
I've observed the following issue. If i have a field of type NSNumber and within the json this field has a String value the conversion works (which is odd). On the other hand if i have a field of type String and within the json this field has a numeric value the app crashes with the following message: [__NSCFNumber length]: unrecognized selector sent to instance. In my opinion in both cases the conversion should just be skipped and a warning should be logged. I hope i could descripe the issue well enough. If you need more information just ask.

**Comment by evermeer** [comment]
Comparing the types before setting the values is not so easy. The dictionary from the json string will contain NSString, NSNumber, arrays and dictionary values. The object itself will have Swift.String, Swift,Int, Swift.Int64, Swift.Double, various enums and other values. The types are almost always different.

Besides that the check should also not break the workarounds that are in WorkaroundsTests.swift.

I would rather turn it around and also set the value when you are trying to put a number into a string. That would mean I only have to add 1 exception when setting the value.  You have a property that has the same name in the json. the chance is big you want that json value in your object anyway.

**Comment by evermeer** [comment]
I have added the exception where a NSNumber can be set to a string property in the latest release 2.4.6. I would like to know what your idea is regarding that workaround. What objections could you thing of for solving it this way. 

As an alternative I could also skip setting the value in the 2 specific situations (string to number and number to string) But then what happens when you have a string and someone forgot to set the quotes around a number in the json. I think I still favorite setting the value over not setting the value.

**Comment by kukudas** [comment]
Your solution is ok. The only objection i see right now is that it can cause confusion why this is possible.

**Comment by evermeer** [comment]
Thanks, then I will leave the fix as it is now.
