### ISSUE TITLE
What can I do with "ERROR: Invalid json!"

### ISSUE THREAD

**Issue by lauthu** [evermeer/EVReflection#133]
Hi, @evermeer . Can I get the nserror when trying to deserialize some object? I saw the console output "ERROR: Invalid json!", But didn't know what can I do with it.

**Comment by evermeer** [comment]
You will see that error when the json that you are using is not valid. You will get that when the Apple function JSONSerialization.jsonObject returns an error.

If you want to see what's wrong with the json, then try to parse it using a validator like https://jsonformatter.curiousconcept.com

I just pushed version 3.1.3 to GitHub and Cocoapods where that message is extended with information from the error. Since it of type ErrorType the only thing that can be added is the localizedDescription. 

You can find a unit test that will show these errors here:
https://github.com/evermeer/EVReflection/blob/master/EVReflection/EVReflectionTests/EVReflectionJsonTests.swift#L98
It will output this:

```
Test Case '-[EVReflection_iOS_Tests.EVReflectionJsonTests testInvalidJsonOrObject]' started.
2016-10-26 10:28:06.390 xctest[48792:1220743] 

===>This will generate an error because you can't create a dictionary for invalid json
ERROR: nil is not valid json!
2016-10-26 10:28:06.391 xctest[48792:1220743] 

===>This will generate an error because you can't create a dictionary for invalid json
ERROR: Invalid json! The data couldn’t be read because it isn’t in the correct format.
2016-10-26 10:28:06.397 xctest[48792:1220743] 

===>This will generate a warning because you can't create a dictionary for a non NSObject type
WARNING: EVReflection can only be used with types with NSObject as it's minimal base type
2016-10-26 10:28:06.398 xctest[48792:1220743] 

===>This will generate an error because you can't create a dictionary for invalid json
ERROR: Invalid json! The data couldn’t be read because it isn’t in the correct format.
2016-10-26 10:28:06.399 xctest[48792:1220743] 

===>This will generate an error because you can't create a dictionary for invalid json
ERROR: Invalid json! The data couldn’t be read because it isn’t in the correct format.
Test Case '-[EVReflection_iOS_Tests.EVReflectionJsonTests testInvalidJsonOrObject]' passed (0.032 seconds).
Test Suite 'EVReflectionJsonTests' passed at 2016-10-26 10:28:06.401.

```
