### ISSUE TITLE
Feature Request: Extension Hearst-DD/ObjectMapper

### ISSUE THREAD

**Issue by muescha** [evermeer/EVReflection#154]
is there any extension planend to use with https://github.com/Hearst-DD/ObjectMapper?

**Comment by evermeer** [comment]
What do you mean? EVReflection is already an object mapper as much as ObjectMapper is. As far as I can see there is no functionality in ObjectMapper that is not in EVReflection. 

I'm always looking for options that I can extend EVReflection with. So if you see some functionality that is related to object mapping, then just let me know. 

You could also extend your ObjectMapper objects with the EVReflectable protocol. I'm not sure why you would want it, but it's possible. You could even create your own protocol for that using: 
`protocol ReflectableMappable : EVReflectable, Mappable { }`

**If you want to compare the 2 mappers, then:**
EVReflection is easier to use because you don't have to write the init and the mapper function. That mapping is handled by EVReflection. I know that EVReflection is a little slower than other object mappers. Using reflection instead of directly assigning values will always be slower. But on a network call it won't matter that it takes 0,01 second longer to parse the json.

**Comment by muescha** [comment]
I looked for a solution to make the `map[]` init of ObjectMapper more easy. But I forget to read again your README and looked short over the big extension list and I was thinking EVReflection is only a reflection interface pluggable for other libraries. 

But you are right. Both are full object mappers and my question makes absolutly no sense. 

Sorry for the confusion. 

Thank for your very detailed answer.
