### ISSUE TITLE
How to serialize enum's value

### ISSUE THREAD

**Issue by szantogab** [evermeer/EVReflection#161]
Hi,

I would like to serialize an enum based on its value: 

enum PartnerType: Int {
    case gastro = 2
}

var type: PartnerType = .gastro

So in this case "type": "2" should be serialized from the type property.

Is this currently possible?

Thanks,
Gabor

**Comment by evermeer** [comment]
Yes, thats possible. Unfortunately you do need a small workaround to make it work. You need to add the EVRaw protocol to your enums and in your object you need to handle the 'setValue forUndefinedKey'

A sample class defenition can be found here: https://github.com/evermeer/EVReflection/blob/master/UnitTests/EVReflectionTests/EVReflectionIssue88.swift#L66

**Comment by szantogab** [comment]
That's cool, thank you! :)

Do you plan to improve upon this? It would be awesome to be able to define serializers / deserializers for a specific type.

**Comment by evermeer** [comment]
Swift does not support setting enum properties using reflection code (setValue forKey) Because of this you will always need to implement the (setValue forUndefinedKey)

The second thing is that in Swift you can only get the rawValue of an enum using reflection when you can also cast it to a protocol like EVRaw. 

So the current version is the maximum for enums what's possible with Swift. (as far as I know)

Currently all propertyMapping and propertyConverters are field specific and not type specific. In general serialisation and deserialisation works without the need of any code. Only in a couple of specific situations (like enum) a workaround is required. See the EVReflectionWorkaroundsTests for details about the other situations. 

It is my intention to eliminate the workarounds if it's possible or to make them easier to use. I think that with the current swift version I am already on the limit what's possible. The only possible improvement could be the implementation of using unsave pointers. I would like to prevent that because the chance and consequences of an error would be large.

If you can think of any other improvements then just let me know and I will see if I can implement it.

**Comment by szantogab** [comment]
Ok, thank you! One last question:

If I'd like to serialize and deserialize an NSDate, how can I do that? Do I need to do it through `propertyConverter` ?

**Comment by evermeer** [comment]
No, You could just define it as a Date (or NSDate but that's more an old Objective-c notation)

Then it will use the default DateFormatter which is:

        dateFormatter = DateFormatter()
        dateFormatter!.locale = Locale(identifier: "en_US_POSIX")
        dateFormatter!.timeZone = TimeZone(secondsFromGMT: 0)
        dateFormatter!.dateFormat = "yyyy'-'MM'-'dd' 'HH':'mm':'ssZ"

You could change it to whatever you want using something like:

        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd"
        EVReflection.setDateFormatter(dateFormatter)

Only in the case that you have various date formatting in your app you have to use the propertyConverters

**Comment by szantogab** [comment]
That's awesome, thank you so much for your effort! :)

**Comment by szantogab** [comment]
One more question :)

Is it possible to convert a UNIX timestamp from JSON to Date? Because with the DateFormatter solution you mentioned above, I am not able to set a format that accepts a timestamp.

**Comment by evermeer** [comment]
A standard DateFormatter is used. When I google for UNIX timestamp and DateFormatter I see:
http://stackoverflow.com/questions/12161369/ios-specifying-unix-time-in-nsdateformatters-format-string

I think you need to use a propertyConverter that calls a function like the one that is mentioned in the stackoverflow post.

But maybe you should make the field a NSTimeInterval instead of a Date?

**Comment by szantogab** [comment]
I think `Date(timeIntervalSince1970: timestamp)` will do the job for me. I just wanted to know whether there is a possibility in your library to do it an easier way, but I'll stick to propertyConverter for now. :)
