### ISSUE TITLE
Crash in EVReflection.toDictionary method

### ISSUE THREAD

**Issue by kerem1905** [evermeer/EVReflection#169]
Hi,

Not often but sometimes crash occurs in EVReflection.toDictionary method, I added the crash report,
Btw,
I am using AlamofireJsonToObjects, not EVReflection directly  

[issue_9_crash_aa19fe9acf56499eaadef5c599e7ebda_4c2c635dc5064183add553ef77df8cef_0_v1.txt](https://github.com/evermeer/EVReflection/files/830615/issue_9_crash_aa19fe9acf56499eaadef5c599e7ebda_4c2c635dc5064183add553ef77df8cef_0_v1.txt)

**Comment by evermeer** [comment]
It looks like the problem is in this part of you crash log:

```
0  libobjc.A.dylib                0x192396f7c objc_msgSend + 28
1  libswiftFoundation.dylib       0x10275ee8c _TFE10FoundationCSo19NSMutableDictionaryg9subscriptFP_GSqP__ + 112
2  libswiftFoundation.dylib       0x10275edb4 _TToFE10FoundationCSo12NSDictionaryg9subscriptFP_GSqP___merged + 172
3  EVReflection                   0x101621594 specialized static EVReflection.toDictionary(NSObject, conversionOptions : ConversionOptions, isCachable : Bool, parents : [NSObject]) -> (NSDictionary, NSDictionary) (EVReflection.swift:163)
```

So I guess it should be in this piece of code:

```
        if isCachable {
            if let p = properiesCache[key] as? NSDictionary, let t = typesCache[key] as? NSDictionary {
                return (p, t)
            }
        }
```

I don't see anything that could cause this crash. Did it ever happen while debugging? If so, was it indeed on this line of code? Could you see any extra information? 

Besides that, you should switch to: 
`pod 'EVReflection/Alamofire'
`
That one will be maintained pro active. AlamofireJsonToObjects will be maintained reactive.

**Comment by evermeer** [comment]
If this is still an issue, then please reopen and provide me some details.

**Comment by evermeer** [comment]
This could have been a threading issue. I have just pushed version 4.6.0 to GitHub with a fix for this. Cocoapods publish is now running (will take 20 minutes)
