### ISSUE TITLE
EvReflection  toDictionary conversion

### ISSUE THREAD

**Issue by vinicius8488** [evermeer/EVReflection#175]
Hi guys,
I Have the following class : 
```
class JsonDomain : EVObject {
 func jsonValue() -> NSDictionary {
        return self.toDictionary()
   }
}
```
and 
 ```
class TokenValor :JsonDomain {
    var to : Token!
    var valor : NSDecimalNumber = 0

    convenience init(to : Token?, valor : NSDecimalNumber?) {
        self.init()
        self.to =  to!
        self.valor = getOptionalDecimalValue(valor)
    }

    override func jsonValue() -> NSDictionary {
        let cifrado = Token()
        cifrado.chave = CryptService.cifrar(to.chave)
        let tokenValor = TokenValor(to: cifrado, valor: self.valor)
        return tokenValor.toDictionary()
    }


    override func getValidationsArray() ->  JsonTypeValidation {
        return [("to","Token"),("valor", "Valor")]
    }
}
 

```

And the method jsonValue()  is returning me : 
{
    to = "Token = {\n  \"chave\" : \"-100;76;-79;81;81;-18;76;23;\"\n}";
    valor = 50;
}
this is giving me the following error: "Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid type in JSON write (MyApp.Token)'"
 
I am currently using version EvReflection with branch : "Swift3" when using swift 2 with version EvReflection 2.6 did not give this error

Thanks for attention

**Comment by evermeer** [comment]
instead of branch Swift3 you should use the master branch. The Swift3 branch is a leftover from when Swift3 was still beta. I just removed that branch. Could you please try it again with the master branch?

One other thing:
Since you set the to field in the init, you could remove the exclamation mark.
you are setting the self.to with an exclamation mark while the to field in the init an optional is. You should remove both the exclamation mark and the question mark.

```
class TokenValor :JsonDomain {
   var to : Token
   var valor : NSDecimalNumber = 0

   convenience init(to : Token, valor : NSDecimalNumber?) {
       self.init()
       self.to =  to
       self.valor = getOptionalDecimalValue(valor)
   }

```

**Comment by vinicius8488** [comment]
Hello my friend, now it worked.
Thank you very much.
Have a nice day.
