### ISSUE TITLE
Getting back basic value without key as response

### ISSUE THREAD

**Issue by krisanthony** [evermeer/EVReflection#180]
Hey again, running into an issue where the endpoint returns something like:

`0` or `243234`

not inside dictionary.

How would I handle this with EVReflection? Haven't been able to get it to work by mapping it into a dictionary like we did for an array of dictionaries.

**Comment by evermeer** [comment]
Hi, question, are you trying to directly parse that object yourself with something like:
`let myObject = TheObject(json: result)
`
then you could just change the result into valid json with something like:
`let myObject = TheObject(json: "{'fieldName': '\(result)'}")
`
If you are using Alamofire or Moya, then you could intercept the result and do the same. 
So you will be correcting the response from the server into valid son before you continue parsing it.

One other solution would be to override the init(json: String) function in your object and then just assign the string to the property.

There are probably more ways to solve this. It would help if you could show me a code snippet.

**Comment by krisanthony** [comment]
Hey so I am using EVReflection with AlamoFire (the dataResponse auto-serialization). I can do a custom request for this one endpoint, but ideally we could handle it in the same way as all other endpoints. We have since simply changed the response to return JSON, but would still be handy going forward in case an endpoint cannot be changed.

**Comment by evermeer** [comment]
You could use your own DataRequest class and clean up the data right before this point:
https://github.com/evermeer/EVReflection/blob/master/Source/Alamofire/DataRequest%2BEVReflectable.swift#L52
Maybe you could even make that cleanup function as a parameter of that function so that you could pass it to the responseObject function.

**Comment by evermeer** [comment]
I have decided that a result cleanup like this should not be part of EVReflection. I don't see a way to add something like this that's generic so that it could be used by others. EVReflection is used to parse json and what you have is not json. 

I think solving situations like this could easily be solved outside the library. When using only the EVReflection core you can just cleanup before calling a function. When using the Alamofire extension, then it's not that hard to make a clone of the EVReflection DataRequest extension and add your own cleanup. You could do similar things with the Moya (reactive) extensions.

Or do you see how this cold be made into a generic function so that it could be used only if someone needs it?
