### ISSUE TITLE
Is EVReflection obsolete with the release of Swift 4?

### ISSUE THREAD

**Issue by Minthos** [evermeer/EVReflection#210]
I admit I haven't looked closely at the changes in Swift 4, but it occurred to me that the Codable protocol does pretty much the same thing as EVReflectable does, at least for basic use cases.

What's going to be EVReflection's role in the future? What are the reasons to keep it in a project? If I can lose a dependency that'll make my project lighter and more maintainable.

I don't mean to sound negative, I just figured I'd open a discussion on the issue.

**Comment by evermeer** [comment]
Yes, funny isn't it, that first apples advices us not to use reflection for json (de)serialisation and then implement something almost the same inside the compiler. See the apple blog post https://developer.apple.com/swift/blog/?id=37

But you are right, it's still a good question. I'm already looking what the Codable protocol could do for your json serialisation. So far I think that it's a very good solution for about 80 to 90% of the cases. In the other cases you would definitely want something to give you extra help with your encoding and decoding. I'm now investigating if that should be a new library that is based on the Codable protocol.

Things that I see currently missing in the Codable protocol is things like propertyConverters, validators and easy to use initializers. In 3 of the actual projects that I am working on all of them needed these.

update:
- for propertyMapping you can use `enum CodingKeys: String, CodingKey {`

**Comment by Minthos** [comment]
After reading that blog post I think their opinion was very immature. Good that they listened to reason and came around on the issue.

An extension or something to Codable sounds useful 👍

**Comment by noobs2ninjas** [comment]
I think Ill be using this for quite some time still. Unless Apple somehow has had a change of heart and will now play nice with multiple versions of Swift in relation to frameworks,  I'll have to wait till all the frameworks I use move over, which will probably happen about as quick as the adoption of Swift 3 from 2.

Also, To add to @evermeer point about the adoption of propertyConverters, propertyMapping, and validators, even if they somehow thought of this in advance, I do not see them making it this easy to use or as accessible, not in the first few versions anyway. Even if they do managed to get there, I see a similar issue with deserializing. 

From what we know about most new API's Apple releases into the wild, there will always be a place out there for frameworks that make dealing with them easier. So, if anything, I think a version for Swift 4 could do exactly that. If nothing than to add custom initializers for JSON/String data.  One thing that I am 99% sure about is they definitely WONT have easy to use methods like 
let data = [MyObject](json: myJson)

**Comment by evermeer** [comment]
@noobs2ninjas I do have to admit that Apple's Codable does look very promising. I was trying to create an initialiser for an object for it. My next step would be an initialiser for an array. Unfortunately JSONDecoder will then give you an error (Cannot get single value decoding container -- found keyed container instead.)
Below is my attempt for this. the fromJson function works and the almost identical init does not. 
I think the cause Is that the type is returned as an optional. Maybe I can find out how to change that.

I also expect the migration from swift 3 to 4 will go faster than from 2 to 3. The conversion for my projects was very easy. If a project is not updated, then it's even ok to just do the conversion yourself in a fork.

```
func test() {
    let t = TestCodable(naam: "Edwin", id: 1)
    let j = t.toJsonString() ?? ""
    print(j)
    let m = TestCodable.🌀(j)
    print(m.debugDescription)
    let n = TestCodable?(json: j)
    print(n.debugDescription)
}

struct TestCodable : Codable {
    var naam: String?
    var id: Int?
}

extension Encodable {
    func toJsonData() -> Data? {
        return try? JSONEncoder().encode(self)
    }
    func toJsonString() -> String? {
        let data = self.toJsonData()
        return data == nil ? nil : String(data: data!, encoding: .utf8)
    }
}

extension Decodable {
    static func 🌀(_ json: String, keyPath: String? = nil) -> Self? {
        guard var data = json.data(using: String.Encoding.utf8) else { return nil }
        do {
            if let keyPath = keyPath {
                let topLevel = try JSONSerialization.jsonObject(with: data, options: JSONSerialization.ReadingOptions.mutableContainers)
                guard let nestedJson = (topLevel as AnyObject).value(forKeyPath: keyPath) else { return nil }
                let nestedData = try JSONSerialization.data(withJSONObject: nestedJson)
                data = nestedData
            }
            let t: Self.Type = Self.self
            print("Type = \(t)")
            return try JSONDecoder().decode(Self.self, from: data)
        } catch {
            print("🆘 ERROR 🆘 \(error)")
            return nil
        }
    }

    init?(json: String, keyPath: String? = nil) {
        guard let obj = Self.🌀(json) else { return nil }
        self = obj // Won't work...
    }
}
```

The output is:

```
{"id":1,"naam":"Edwin"}
Type = TestCodable
Optional(PerformanceTest.TestCodable(naam: Optional("Edwin"), id: Optional(1)))
Type = Optional<TestCodable>
🆘 ERROR 🆘 typeMismatch(Swift.SingleValueDecodingContainer, Swift.DecodingError.Context(codingPath: [], debugDescription: "Cannot get single value decoding container -- found keyed container instead."))
nil
```

**Comment by evermeer** [comment]
Since it's more a collection of snippets, I now created a subspec to my Stuff library for the Codable functions. For more info see https://github.com/evermeer/Stuff#codable

You can use the following functions:
```swift
let json = yourEncodableObjectInstance.toJsonString()
let data = yourEncodableObjectInstance.toJsonData()
let newObject = YourCodableObject.decode(json: json)
let newObject2 = YourCodableObject.decode(data: data)
let objectArray = [YourCodableObject](json: json)
let objectArray2 = [YourCodableObject](data: data)
let newJson = objectArray.toJsonString()
```

 It seems like it's not possible to crate a function like
```swift
let newObject = YourCodableObject(json: json)
```
because there is no way to call a super.init function which is needed to initialise the object.

**Comment by evermeer** [comment]
I guess this discussion can be closed since everybody agrees that Codable will be a valuable protocol that could be used in most cases when doing json parsing.

**Comment by valleyman86** [comment]
I would like to point out that after looking at the source for Codable I do not believe that Apple is using reflection. They use a lot of protocols, generics and extensions for all the types necessary in swift. You still need to create an initializer that sets each property manually. Apple gets around it by creating default initializers that do this for you unless you need to do anything different. If you do then we are back to almost square one and having to map properties ourselves. 

Honestly the biggest benefit I am seeing from Codable now (unless you don't need to remap any keys) is making it a bit cleaner to parse JSON rather than messing around with raw dictionaries and arrays and casting their values.

**Comment by Dimillian** [comment]
I wanted to add my input, switched all my projects from using custom Reflection mapping and sometime EVReflection to pure Codable. In some edge cases I need to write some manual encoder and decoder, but it's a plus rather than a downside, the API is very close to NSCoding in the end. 
I'm consuming a rather complex API, and I feel like Codable do the job very well now.

**Comment by evermeer** [comment]
@Dimillian Just curious... Did you use https://github.com/evermeer/Stuff#codable or did yo write your own code for doing this?
