### ISSUE TITLE
Map response to array of arrays with RxSwift extension

### ISSUE THREAD

**Issue by AndrejJurkin** [evermeer/EVReflection#233]
Hello again!

Is it somehow possible to automatically map a response into "array of arrays" e.g. [[EVObject]], could not find anything on that subject, I guess it's quite rare.

I'm looking to get something like this:

    func getNutritionHistoryData(date: Date) -> Observable<[[NutritionHistory]]> {
        
        return self.provider.request(.nutritionHistory(date: Date))
            .map(toArray: [NutritionHistory]) // ???
    }

**Comment by evermeer** [comment]
Hi, I think that doing a
`.map(toArray: [NutritionHistory].self)`
already works. Or do you have a problem with it?

**Comment by AndrejJurkin** [comment]
Well, neither  `.map(toArray: [NutritionHistory]) ` nor  `.map(toArray: [[NutritionHistory]])` works for me, I get a compile time warning - Extraneous argument label 'toArray' in call. 

```
func getNutritionHistoryData(date: Date) -> Observable<[[NutritionHistory]]> {
    
    return self.provider.request(.nutritionHistory(date: Date))
        .map(toArray: [NutritionHistory]) 
}
```

**Comment by evermeer** [comment]
Ah, I should have checked it...
You have to specify the type where it maps to. So for a regular object array it would be:
`.map(toArray: NutritionHistory.self)`
And then for an array of arrays of that object  it should be:
`.map(toArray: [NutritionHistory].self)` 
but...
It can currently only map to a type that implements EVReflectable and I don't think an array of EVReflecable objects does. I have to check because there is an extension active on Array.. 
I will have a look at it this weekend.

**Comment by evermeer** [comment]
I had to create extra functions for this. Unfortunately this also means that it only works for nested arrays and not nested nested arrays. because of the Switch to Swift 4 I also had to use Moya 10.0 which is still in beta. Because of this I had to change function names to avoid conflicts. For the nested arrays there is now a function called RmapNestedArray. Moya 10 also works a little different. See the unit tests to see a demo.

In order to use this using cocoapods you have to specify the git pad so that it will use master
`pod 'EVReflection', :git => 'https://github.com/evermeer/EVReflection.git'`

If you also use Moya, then you also have to add this:
`pod 'Moya', :git => 'https://github.com/Moya/Moya.git', :branch => '10.0.0-dev'`

**Comment by AndrejJurkin** [comment]
Perfect thanks, I use my custom solution for the moment, you can close the issue.
