### ISSUE TITLE
Cannot call value of non-function type 'String'

### ISSUE THREAD

**Issue by x128** [evermeer/EVReflection#236]
Xcode 9 final. Create a new project, init pods with this podfile:

```
use_frameworks!

target 'MyTarget' do
  platform :ios, '9.0'

  pod 'AFNetworking'
  pod 'EVReflection/XML'
  pod 'KeychainSwift'
end
```

Then try to compile.
Result - 2 build errors:
**Cannot call value of non-function type 'String'** in EVReflection.swift, lines 977 and 978.

Not only compiler: code editor also highlights **type**(of:) as a String ([illustration](https://habrastorage.org/web/502/39e/829/50239e8292184d34bc49c60ae1f871e0.png)).

Tried Swift 3.2 and 4.0.
So, we can just rename `type` (String).

**Comment by marinnikolic** [comment]
Hi, I got the same problem here.

**Comment by evermeer** [comment]
I'm working on an update. I have some RxSwift / Moya version issues to fix.
For now I think you could do a quick fix by changing those 2 errors from:
`type(of:`
to:
`Swift.type(of:`

**Comment by evermeer** [comment]
I switched master to Swift 4

Unfortunately I'm not allowed to push a new version for this to cocoapods because there now is a dependency to Moya 10.0 which is still in beta. 

In order to use this using cocoapods you have to specify the git pad so that it will use master
`pod 'EVReflection', :git => 'https://github.com/evermeer/EVReflection.git'`

If you also use Moya, then you also have to add this:
`pod 'Moya', :git => 'https://github.com/Moya/Moya.git', :branch => '10.0.0-dev'`
