### ISSUE TITLE
Unable to update to v5.0 using CocoaPods

### ISSUE THREAD

**Issue by valeriologiudice** [evermeer/EVReflection#241]
CocoaPods is not installing the latest version. It keeps using EVReflection (4.19.1). Even if I force to download v5.0 like this pod 'EVReflection', '~> 5.0' it doesn't find it and trows an error. What should I do? Thanks.

**Comment by evermeer** [comment]
EVReflection has a dependency with Moya. Unfortunately The Swift 4 version of Moya (10) is still in beta. Because of that the EVReflection 5.0 version cannot be published to cocoapods. If you do want the 5.0 version then you have to specify that you want the latest version from git. You can do that by putting the following in your podile:

`pod 'EVReflection', :git => 'https://github.com/evermeer/EVReflection.git' `

The moment Moya 10 is released I will also push the 5.0 version to cocoa pods.
