### ISSUE TITLE
Classes with EVObject attributes from another frameworks 

### ISSUE THREAD

**Issue by hugowschneider** [evermeer/EVReflection#25]
Hi,

I think I found a bug and maybe I found a workaround. I am working with EVObjects in a framework. And I noticed that this attributes when constructed an object from a dictionary where always `nil` or an empty array.

I found out that the method

``` swift
func valueForAny(parentObject:Any? = nil, key:String? = nil, anyValue: Any) -> (AnyObject, String)
```

was returning only the types name, for example `Class`, and not  `Framework.Class`, the namespace prefix was not present.

I fixed it changing the line 446 of file EVReflection.swift from:

``` swift
var subtype: String = "\(mi)"
```

to:

``` swift
var subtype: String = String(reflecting: mi.subjectType)
```

Hope it helps

**Comment by evermeer** [comment]
Since nested classes will give you an ugly name that start with _Tt I decided to only return the class name itself. When using EVReflection with objects in a framework you can set the correct bundle by calling EVReflection.setBundleIdentifier(ClassInBundle)
Let me know if that works for you.

**Comment by hugowschneider** [comment]
I will try it, but the line of code I used does not return this objc nasty names. It returns something like Swift.Array<Framework.Class>. It maybe easier to use than set a fixed bundle name and it can help to  work with multiple frameworks classes.

**Comment by hugowschneider** [comment]
Sorry, the formatter removed some text from my previous post. The code returns a string like `Swift.Array<Framework.Class>` and your code can handle this string without any problem.

I just took in the EVReflection.setBundleIdentifier method, it seems to force the bundle name for all classes, right? In my case it works, but to work with more than one bundle, will it work too?

**Comment by evermeer** [comment]
You are right. using EVReflection in multiple frameworks will be problematic. I will try to work out a solution for this. It might take a while since It requires more work than adding the bundle name. I probably need a refactor.

**Comment by Dimillian** [comment]
Is it planned ? I'm having the issue now that I split my models between multiple modules. I'm thinking about a workaround tho

**Comment by evermeer** [comment]
As i said in your pull request: Yes, this is still planned.

**Comment by evermeer** [comment]
There is now support for multiple bundle identifiers.

**Comment by evermeer** [comment]
The solution to set multiple bundle identifiers has to be the solution for this. Initially I thought I could do this with automatic detection, but that did not go so well. I am closing this issue because setting the bundle identifiers works good enough.

**Comment by edias** [comment]
I'm not sure the bundle identifier will work quite well in a scenario with multiple targets. 

For example, let's suppose I have an app called "MyApp"with 3 different targets:

1- "MyAppDev"
2- "MyAppQA"
3- "MyAppProd".  

Let's say now I have a class called Foo, the full name of this class including module would be MyApp.Foo. However, if a compile this class with "MyAppDev" target, the main bundle name will be called "MyAppDev" and then strategy of concatenating BundleName + ClassName will become MyApDev.Foo and serialization will fail. 

I think an easy way out would be adding another setBundleIdentifier where a string can be passed instead of passing a class and letting the EVReflection to find out the bundle name by itself.

Please let me know your thoughts @evermeer

**Comment by evermeer** [comment]
@edias You can now use the setBundleIdentifier with a string (in the Swift3 branch)
