### ISSUE TITLE
Help with mapping XML

### ISSUE THREAD

**Issue by chrisleversuch** [evermeer/EVReflection#250]
I have an XML object where some keys can have 1 or more children. This is mapped to an Array in swift. When the key has more than 1 child, everything works fine but when it only has 1 it doesn't work. The setValue:forUndefinedKey: method gets called instead.

Is there an easy way to handle this? I've started creating custom property converters where I have to check if the decodeConverter value contains a dictionary or an array of dictionaries but I'm hoping there's an easier way.

**Comment by evermeer** [comment]
Sorry for the late response... I have been busy...

Let me see if I understand correctly. So an XML like this goes ok:
```
<root> 
<item><value>a</value></item>
<item><value>a</value></item>
</root>
```

but an XML like this fails:
```
<root> 
<item><value>a</value><valueb>b</valueb></item>
<item><value>a</value><valueb>b</valueb></item>
</root>
```
That's probably because your root object needs a property item which is an array of objects. I think your object definition should be something like:

```
class root: EVObject {
   var item: [value] = []
}

class item: EVObject {
  var value: String?
  var value: String? 
}
```

If you show me your XML I can give you the object structure that would work for it. In 99% of the case you would not need any special converters.

**Comment by evermeer** [comment]
Just let me know it this is still something that you need help with.
