### ISSUE TITLE
Parsing JSON array conversion model slow speed, how can increase the speed, thanks

### ISSUE THREAD

**Issue by WMSmile** [evermeer/EVReflection#261]

**Comment by evermeer** [comment]
Using Reflection will always be the slowest way to map JSON to objects but also the easiest way. But then even if you have a JSON file of 100KB which has 1000 objects, it should be able to parse it in a second. For a normal API response it usually is parsed in milliseconds. The network call itself would normally take 99% of the time.

Since the release of Swift 4 you could start using Codable. Then most of the object mapping code will be generated compile time. That would be the best alternative. Libraries like Alamofire and Moya also added support for Codable. If you want to do the object mapping yourself, then you could use these handy helper functions: https://github.com/evermeer/Stuff#codable

**Comment by WMSmile** [comment]
thanks
