### ISSUE TITLE
Combining  Object, EVNetworkingObject  for Realm + EVReflectable + Alamo fire in one object. Is it possible?

### ISSUE THREAD

**Issue by steve21124** [evermeer/EVReflection#273]
Combining  Object, EVNetworkingObject  for Realm + EVReflectable + Alamo fire in one object. Is it possible?

some note : 
-https://github.com/evermeer/EVReflection/issues/172 => this using RealmObject and EVObject
-https://github.com/evermeer/AlamofireJsonToObjects => this using Alomofire and EVReflectable

what if need to use Object, EVNetworkingObject  in one object?

`
class WeatherResponse: Object,EVNetworkingObject {
    var location: String?
    var three_day_forecast: [Forecast] = [Forecast]()
}

`

**Comment by evermeer** [comment]
Hi, As you can see at the top of the readme from AlamofireJsonToObjects  that library is now embedded inside EVReflection and maintained there. So if you want to use that plus Realm, then you  can use it by adding the following lines in your pod spec:
```
pod 'EVReflection/Alamofire'
pod 'EVReflection/Realm'
```
EVNetworkingObject derives from EVObject which implements EVReflectable
The Realm Object is extended with the EVReflectable protocol
The Alamofire extension is an extension for DataRequest that is based on the EVReflectable protocol.

So the only thing you have to do is to create class definitions where Object is its base class and extend it with the EVReflectable protocol like this:
```
class Person: Object, EVReflectable {
    @objc dynamic var name = ""
    @objc dynamic var age = 0
    @objc dynamic var spouse: Person?
    let cars = List<Car>()
}
```

The only thing EVNetworking object handles extra is setting the http networking status as a status message to the object. If you do want that in your objects, then just add the 2 functions that are in EVNetworking object into your own classes.

You do have to be aware that if you create a base class for that, then you also have to create default implementations for all optional EVReflectable functions. Otherwise they cannot be overridden if you ever want that inside your objects. If you want to see sample code of that, then have a look at EVObject.

**Comment by steve21124** [comment]
Thank you for the reply. for now, I use Alamofire and return it as a string and from the string converted back to object. it is working.
