### ISSUE TITLE
Trouble mapping dictionary

### ISSUE THREAD

**Issue by Dbigshooter** [evermeer/EVReflection#275]
I'm trying to map the following JSON:

```
{
    "global": {
        "datainfo.alias1": "Info1",
        "datainfo.alias2": "Info2",
        "datainfo.alias3": "Info3"
    },
    "person": {
        "noteinfo1": true,
        "noteinfo2": true
    }
}
```

My model looks like this:

```
class data: EVObject {
    
    var global: [String: Any?] = [String: Any?]()
    var person: [String: Any?] = [String: Any?]()
}
```

However I get some empty output:

```
Optional(data = {
  "global" : {

  },
  "person" : {

  }
})
```

What am I missing?

**Comment by evermeer** [comment]
Swift is limited in its reflection capabilities. Most of EVReflection functionality is based on functions that came from Objective C. Because of this there are a couple of swift specific types that need extra code to handle. One of these is the Swift dictionary. If you look at the console output you will probably see warnings about this passing by.

A quick fix would be changing it to a NSDictionary. If you don't want that, then you need to implement a function like this:

    override func setValue(_ value: Any!, forUndefinedKey key: String) {
        switch key {
        case "global":
            if let dict = value as? NSDictionary {
                self.global = [:]
                for (key, value) in dict {
                    self.global[key as? String ?? ""] = value
                }
            }
        case "person":
            if let dict = value as? NSDictionary {
                self.person = [:]
                for (key, value) in dict {
                    self.dict[key as? String ?? ""] = value
                }
            }
        default:
            self.addStatusMessage(.IncorrectKey, message: "SetValue for key '\(key)' should be handled.")
            print("---> setValue for key '\(key)' should be handled.")
        }
    }

A unit test that shows this can be found in the EVReflectionWorkaroundsTests class

**Comment by evermeer** [comment]
Just let me know if you need more help.
