### ISSUE TITLE
Array Crash

### ISSUE THREAD

**Issue by priore** [evermeer/EVReflection#281]
We have define an object contains an array of other objects but when parsing it happens a crash on the array when the json contains an array of strings, not array of objects that we expect, in this case should return an empty array, no ?

```swift
if theValue is Array<Any> {
    return (theValue as AnyObject, valueType, false)
}

```

**Comment by evermeer** [comment]
That's strange,

When you try to put an array of strings into an array of object, you should get a warning in your console output like this:
`🌀 ERROR: Invalid json! The data couldn’t be read because it isn’t in the correct format.`
As you can see in this unittest:
https://github.com/evermeer/EVReflection/blob/master/UnitTests/EVReflectionTests/EVReflectionTests.swift#L489

Could you show me a little more like the json variations that you try to parse and the object definition?

**Comment by evermeer** [comment]
Did you find out what went wrong? Can I close this issue?

**Comment by priore** [comment]
sorry I haven't tried yet

**Comment by evermeer** [comment]
Just let me know if this is still a problem.
