### ISSUE TITLE
 failable initializers

### ISSUE THREAD

**Issue by neil-wu** [evermeer/EVReflection#39]
Since swift support failable initializers, we can use it in our project. For example, if we pass a invalid json string to the initializer,  we can return nil value.

**Comment by evermeer** [comment]
Currently EVReflection is robust. Even if the json does not match the target object it tries to map as much fields as possible. I think I would like to keep it that way. Otherwise the parsing will fail the moment there is a minimal change to the json. Then the only place where a failbalbe initializer could be used (and failing) is when the NSJSONSerialization.JSONObjectWithData function could not return the data.
