### ISSUE TITLE
Is there a way to serialize CGPoint even though it is a struct ? 

### ISSUE THREAD

**Issue by ghost** [evermeer/EVReflection#61]

**Comment by evermeer** [comment]
At the moment there is no support for structs besides a couple of specific ones like a custom dictionary and array with nullable objects. (see the workaround tests). The issue is that the structs needs to be converted to an AnyObject. In the case of a CGPoint (and maybe CGRect) I think we could handle it as a Dictionary (with x and y values). Let me think about the option to do a default conversion of structs to a dictionary. You could then also use the setValue forUndefinedKey when restoring data.

**Comment by ghost** [comment]
Thank you for your answer ! 
I actually thought that it might be useful in case of CGPoint and CGRect to use their methods:
CGPointFromString, NSStringFromCGPoint, CGRectFromString,NSStringFromCGRect but I am not sure if this will corrupt the json format - I guess that your solution is more general and will apply for any struct. 
If you are interested I might be able to contribute by implementing an agreed solution. 

On a different note - I find this library very useful with a very clear API so lots of compliments for that !

**Comment by evermeer** [comment]
Thanks :) I always try to make it as easy as possible to use which as much support as possible.

You are right. For creating json I use the default NSJSONSerialization which does not support things like CGPoint and CGRect.

**Comment by evermeer** [comment]
Update: I have the serialization working. There are still some small things to do for the deserialisation.

**Comment by evermeer** [comment]
It's now working. I pushed this to GitHub and Cocoapods as version 2.23.0
You can find a unit test to see how it works at:
https://github.com/evermeer/EVReflection/blob/master/EVReflection/EVReflectionTests/EVReflectionWorkaroundsTests.swift#L70
