### ISSUE TITLE
If Product Module Name is set in Build Settings, swiftClassTypeFromString() fails

### ISSUE THREAD

**Issue by rafcabezas** [evermeer/EVReflection#65]
`swiftClassTypeFromString()` calls `getCleanAppName()` to create the class string name; the problem is that the class name is in the form:

**product_module_name.class_name**

not

**app_name.class_name**

In my app at least. This causes `swiftClassTypeFromString()` to return nil and deserialization to fail.

I resolved it by adding

``` swift
        if let klass = NSClassFromString(className) {
            return klass
        }
```

before the end of the `swiftClassTypeFromString()` function. But I wonder if the correct solution is to update getCleanAppName()?

Note that my object is flagged with
`@objc(MyClassName)` so that `NSClassFromString` works directly.

**Comment by evermeer** [comment]
Currently the getCleanAppName does this:

Get the app name from the 'Bundle name' and if that's empty, then from the 'Bundle identifier' otherwise we assume it's a EVReflection unit test and use that bundle identifier.

So in order to let this work correctly you should have the right 'Bundle name' or 'Bundle identifier' in your .plist.

If you do not want to use this functionality, then you can force a specific bundle identifier by using the setBundleIdentifier function.

I do think that your addition is a good one. I think I will put it in the beginning of the function. It would eliminate the need for the check for class names that start with _Tc. I will add the in the next version (maybe later today) 

Thanks for reporting this and even giving pointers how it can be solved!

**Comment by rafcabezas** [comment]
Great, thanks Evermeer!
I believe in most apps the product module name is the same as the bundle name.
The default for the product module name is: $(PRODUCT_NAME:c99extidentifier)
We override this, causing this problem. But this is why I wonder if getCleanAppName should get the name from the product module name.

Thanks for the great work!

Raf.

PS: Just found out that the class name now (since Swift 2.1.1) can be retrieved by using String(MyClass). See http://stackoverflow.com/questions/24494784/get-class-name-of-object-as-string-in-swift

**Comment by evermeer** [comment]
Thanks for the tip.... I will look into it.

**Comment by evermeer** [comment]
I just pushed your solution to version 2.22.2
Please give it a try to see if it works for you.

**Comment by rafcabezas** [comment]
I will today. Thank you!

**Comment by rafcabezas** [comment]
It's working. Thank you!.

**Comment by edias** [comment]
After annotating the classes like @rafcabezas things start working to me as well. The only drawback on this solution is that I have to annotate all classes with @objc.

I think another solution to this issue would be adding another setBundleIdentifier method where a bundle string could be passed instead of leaving EVReflection to figure out by itself.

Let me know your thoughts @evermeer

**Comment by evermeer** [comment]
@edias You can now use the setBundleIdentifier with a string (in the Swift3 branch)
