### ISSUE TITLE
Handle JSON to Object mapping mis match

### ISSUE THREAD

**Issue by edias** [evermeer/EVReflection#77]
When a JSON object returned from the server is different from the object expected on the client, the serialized object just make it empty and do not return any error.

For example:

**Client object expected**

class UserInformation:EVObject
{
    var username:  String?
    var password:  String?
}

**Server object sent**

{error:"An error message"}

**Result**

Result object returns with success, empty UserInformation and no errors

**Expected**

Result object returns with serialization error and nil Result.value

**Comment by evermeer** [comment]
EVReflection is build to be able to handle all json without crashing. In this case your object should have a property named error of type String. If this could happen to all your objects, then you could put that property in a bass class.

That is also how I did this in my EVWordpressAPI library. See:
https://github.com/evermeer/EVWordPressAPI/blob/master/EVWordPressAPI/EVWordpressData.swift#L10

I think returning an error and not trying to map what's returned will make your app vulnerable for change to the used API. You don't want existing app users to be forced to download a new version when the API maker added a field to the response.

But you are right that it could be handy when extra information was returned indicating what is exactly wrong with the json. Maybe something like a collection with fields that could not be mapped. I will let this sink in and think about what's the best solution for this.

**Comment by edias** [comment]
You can still handle that scenario without crashing the app. When serialization fail just return a result with no value and a NSError. Otherwise any data sent from the server will be considered success and there will be no way to the App know what is going on. 

Perhaps you can find some inspiration on JSONModel (https://github.com/icanzilb/JSONModel/blob/master/README.md#magical-data-modelling-framework-for-json). They handle this scenario.

`Result<Object, NSError>` => Object here would be nil and error would exist with fields matching issue

**Comment by evermeer** [comment]
I am trying to figure out how this should be handled. The following issues come to mind:
- I do not want to raise an error for every miss match. It could be for a good reason that values are somtimes missing from the JSON
- I do not want to change properties so that there is extra information about what should be expected from the JSON. For instance i want to keep it a String and don't want to make it an JsonRequired<String> or JsonOptional<String> because things like that would eliminate the bennefits of using reflecton.
- A mismatch could also mean that there are extra keys in the json. These could be valid. For instance a new API version could have extra data that we don't need. It's ok to report these, but you should be albe to ignore that.
- EVReflection is using object initializers for easy construction of objects based on JSON. You don't want them to fail because then you also could not pass on information about the reason why it failed. So any problem should be reported in a status property in that object.

Possible solution:
Currently mismatches will only be logged to the output window. Those could be put in a Status object so that you can have a type and a description that will be added that to an array in the object itself. If one of the child objects has a status messages, then one aggregated status message will be added about that to its parent object so that it's easy to validate one complex structure parsing.

Currently all properties will be optional. In order to be able to make properties required we can add an extra function like there is for propertyMapping for handeling extra validation. This function will be called with the data as a dictionary (the json will already be parsed to a dictionary). In that same function there could also be a check for keys that should not exist (like error). Besides that there could also be a custom validation that also adds to the same status array. The function will then look like this:

```
func initValidation(dict: NSDictionary) {
   self.initMayNotContainKeys(["error"])
   self.initMustContainKeys(["requiredKey1", "requiredKey2", "requiredKeyEtc"])
   if self.mySpecialCustomValidation(dict) {
      self.addStatusMessage("type", "message") // this could also be called in property specific validators
   }
}
```

Any mismatch will again be reported in the status message of the object like described above. It's up to the situation where you create an object to handle any status messages.

Do you think there is a better solution for solving this?
What other validations should there be?

**Comment by edias** [comment]
I think the validation should go from the object to the JSON. JSON attributes not declared on the objects as properties should be 'relaxed' on the serialization. However, object properties should be mandatory unless they are set as ignored by a function as you suggested. 

`

```
class func checkKeyMappingMatchJSONData<T:EVObj>(object:T, json:String)->NSError?
{
    let jsonDict = EVReflection.dictionaryFromJson(json)
    let (properties, _) = toDictionary(object)

    let objectProperties   = Set(properties.allKeys as! [String])
    let ignoredProperties  = Set(object.ignoredProperties())
    let requiredProperties = objectProperties.subtract(ignoredProperties)
    let jsonkeys           = Set(jsonDict.allKeys as! [String])

    //check for missing keys
    if(!requiredProperties.isSubsetOf(jsonkeys))
    {
        //get a list of the missing properties
        let missingProperties = requiredProperties.subtract(jsonkeys)

        let errorDescription:String = "\nSerialization Error: The JSON data is missing some keys specified on the class '\(EVReflection.swiftStringFromClass(object))'. The following keys are missing: '\(missingProperties)'";
        NSLog(errorDescription)

        return NSError(domain: errorDescription, code: 0, userInfo: nil)
    }
    return nil
}
```

`

`func ignoredProperties() -> [String]
 {
     return ["myIgnoredProperty"]
}`
- I do not want to raise an error for every miss match. It could be for a good reason that values are sometimes missing from the JSON

> You don't have to scan the entire tree to find out all missing properties of all objects. Just return an error on the first object that have a miss match from the object to the JSON data.
- I do not want to change properties so that there is extra information about what should be expected from the JSON. For instance, I want to keep it a String and don't want to make it a JsonRequired or JsonOptional because things like that would eliminate the benefits of using reflection

> You are right about that, don't do it. Just make by default all properties declared as required and in case you want to set it as optional, just create an ignoredProperties function on the object.
- A mismatch could also mean that there are extra keys in the json. These could be valid. For instance a new API version could have extra data that we don't need. It's ok to report these, but you should be albe to ignore that.

> Exactly, so perform validation from the Objects to the JSON. So developers will have more control over the serialization.
- **EVReflection** is using object initializers for easy construction of objects based on JSON. You don't want them to fail because then you also could not pass on information about the reason why it failed. So any problem should be reported in a status property in that object.

> Use **setPropertiesfromDictionary** and instead of returning generic T return an error in case a property on the object is not ignored and is not presented on the JSON. If **setPropertiesfromDictionary** does not return an error, it's because the serialization on that specific object was performed with success, so you can move to the next one.

`
public class func setPropertiesfromDictionary<T where T: NSObject>(dictionary: NSDictionary, anyObject: T, convertionOptions: ConvertionOptions = .Default) -> NSError
`

**Comment by evermeer** [comment]
EVReflection is also used for other things than json serialisation. For instance it's also used in EVCloudKitDao. In that case when you write empty values to CloudKit, you won't get those keys back when you read that record. In that case I don't want all properties to be mandatory by default. Maybe this could be influenced by adding a standard property or protocol declaration to change it from not mandatory to mandatory. 

One other thing to consider for something like this is the property mapping. The dictionaryFromJson does not map keys and the toDictionary does map keys. Because of this there could be a mismatch and the check in your sample code will fail for a json that is actually correct. I would have to find a way to fix that. It would be easier to use a validator as I described above.

I think there are different levels of errors. I do think it would be nice if you got a collection with all problems so that a developer can decide what action should be taken. 

Yes, i could let the setPropertiesfromDictionary also return an error object. But then still users are allowed to use the object initializer. I would like them to be able to react on an error. This could be done by adding an extra property to the object.

I will let this all sink in  a little more before starting to implement this.

**Comment by edias** [comment]
In case you want to change the nature of EVObject property validation, perhaps protocols are the way to go indeed. 

About the dictionaryFromJson not returning keys and having a mismatch, I'm not sure if I got that right...

On EVObject, you could create a public static initializer that receives a dictionary as a parameter and would returns a tuple or something like that containing the new instance or an error object. 

Well...at least you have some ideas to think about...

Let me know if I can help with something else.

**Comment by evermeer** [comment]
Class level deserialisation validation have been added and pushed to CocoaPods and GitHub as version 2.32.0

For more information:
See the documentation: https://github.com/evermeer/EVReflection#deserialisaton-class-level-validations
See the unit test: https://github.com/evermeer/EVReflection/blob/9fdb8a8f4c6bf97af309209c0100fab15f616dfd/EVReflection/EVReflectionTests/EVReflectionTests.swift#L315-L315
