### ISSUE TITLE
How to support custom defined enum

### ISSUE THREAD

**Issue by jtianling** [evermeer/EVReflection#8]
EVObject is strong enough to support custom defined class, but I can't find a way to support the custom defined enum. Is there a way to do that?

**Comment by jtianling** [comment]
Some code here:

``` swift
class StatusInfo: EVObject {
  enum StatusType: Int {
    case NotOK = 0
    case OK
  }

  var status: StatusType?
}
```

**Comment by evermeer** [comment]
Unfortunately this is not possible due to the Swift reflection limitations. There is no way to set a property that is of a type enum. object properties can only be set by executing the method: theObject.setValue(newValue, forKey, key)

You can also see that already in the log. See the message:
WARNING: The class 'StatusInfo' is not key value coding-compliant for the key 'status'

The only workaround for this is by adding a mapping method to your StatusInfo class like:

```
    override func setValue(value: AnyObject!, forUndefinedKey key: String) {
        switch key {
        case "status":
            if let rawValue = value as? Int {
                status = StatusType(rawValue: rawValue)!
            }
        default:
            NSLog("---> setValue for key '\(key)' should be handled.")
        }
    }
```

**Comment by evermeer** [comment]
In the master branch I added your sample as an unit test. I also added this to the known issues section in the readme.

**Comment by evermeer** [comment]
To be sure there is no better workaround available I also posted a question on stack overflow: http://stackoverflow.com/questions/31589405/using-reflection-to-set-object-properties-without-using-setvalue-forkey

**Comment by jtianling** [comment]
I tried the workaround, but found the setValue is right and warning is still here, the most serious problem is when you set a value like that, you can't use the toJsonString, because you will get a json that all the attribute set by that equal to nil.

**Comment by evermeer** [comment]
Last night I added a unit test class called WorkaroundsTests.swift. Sorry, it's only in master at the moment.  But you should be able to copy paste it to the 2.0 branch. That workaround does work for custom enums. Currently it does report an error while populating an object from json, but it's still able to populate the enum value. Later today I will add a test for the toJsonString.

**Comment by evermeer** [comment]
The toJsonString goes wrong because the Swift reflection code is returning the enum as type Any. It looks like it's not possible to get the rawValue from that. I have posted another SO question for that: http://stackoverflow.com/questions/31607629/get-rawvalue-from-enum-in-a-generic-function
I will add the workaround to github later today.

**Comment by evermeer** [comment]
The workaround for enums is now added to the trunk. You only have to add a protocol to each enum.
The enum will then look like this:

```
enum StatusType: Int, EVRawInt {
    case NotOK = 0
    case OK = 1
}
```

I now have a similar bug for the [Testobject?] type. I will try to fix that before merging this to the Swift 2.0 branch

**Comment by evermeer** [comment]
The workaround for arrays with nullable object now also work. I will now start the merge to the Swift 2.0 branch

**Comment by evermeer** [comment]
Swift 2.0 branch is now also up to date (tested with Xcode 7 beta 4)
