### ISSUE TITLE
Allow to change default value of ConvertionOptions

### ISSUE THREAD

**Issue by alex-swiftify** [evermeer/EVReflection#80]
After updating the library via CocoaPods I've noticed that the default value of ConvertionOptions used for EVObject.toDictionary() includes KeyCleanup option by default, while previously KeyCleanup was a boolean field being false by default.
**I'm sure this update may silently break lots of codebases!**

I'm sure I'm not the only one who wants map most property values to JSON without any name conversions, thus I want to change the default value of ConvertionOptions to disable KeyCleanup.
As a workaround, I've changed ConvertionOptions.Default field from let to var, and now I change it during app startup:

> ```
>     ConvertionOptions.Default = [.PropertyConverter, .PropertyMapping, .SkipPropertyValue]
> ```

By the way, I think ConvertionOptions should be named Conver_s_ionOptions for correct spelling.

**Comment by evermeer** [comment]
Well, at least i was consistent :) I replaced 188 incorrect spelling of convertion to conversion

I change the default to a DefaultSynchronize and DefaultDesynchronize and also made them a var instead of let so that it can be changed as you suggested. I have split it into 2 because there is a reasonable chance that you would like different behavior. When going from json to an object, the keyCleanup will only be done when there is a mismatch. So for serialization you would want this enabled. And as you said for deserialization you would want this to be disabled by default. 

I am still doing some tests. I will probably push a new version within an hour.

Thanks for reporting this!

**Comment by alex-swiftify** [comment]
Sounds great - thank you for super fast turnaround!!!
I'll try your changes soon :)

Best Regards,
Alex

**Comment by evermeer** [comment]
I pushed a new version 2.30.0 to CocoaPods and GiHub with this change.

**Comment by alex-swiftify** [comment]
Thank You!

I have a release of my project planned for today, so I’ll check the changes right afterwards :)

Best Regards,
Alex

**Comment by evermeer** [comment]
Good luck with the release!

**Comment by alex-swiftify** [comment]
Hey Edvin,

Just wanted to say thank again!
Everything works as described after your last update.
Thank you for very useful library!

Best Regards,
Alex
