### ISSUE TITLE
Should areEqual use different conversion options?

### ISSUE THREAD

**Issue by vronin** [evermeer/EVReflection#87]
I have a class:

```
class Foo: EVObject {
  var bar: SomeSerializableType
  var baz : SomeUnserializableType  // it's runtime only which isn't persisted

       // Ignore unserializableType
      override func propertyMapping() -> [(String?, String?)] {
        return [("baz", nil)]
    }
}
```

It works fine when I try to serialize and deserialize it. However, if I am trying to compare two object

> var foo1 = Foo()
> var foo2 = Foo()
> 
> if (foo1 == foo2) {
> }

It will spit out "ERROR: valueForAny unkown type SomeUnserializableType for value: AppName.SomeUnserializableType

I checked and apparently areEqual use`conversionOptions: .None`

I think it should use other conversionOptions.

**Comment by evermeer** [comment]
I'm inclined to say that you are right. My initial thoughts with this was that it did not matter what conversion options to execute when comparing objects since they will both do the same conversion. Since functionality is skipped it would be faster. 

But in your case you have data that would be lost because it's not serializable and it will be treated as a nil making all values of that property equal. Clearly you do not want that.

So we have to change it. I think we can then only skip the keyCleanup option. Do you agree? I will make this change this evening (CET)

**Comment by evermeer** [comment]
OK, I had a better idea. I added a new `ConversionOption` named `DefaultComparing` and set it to `[PropertyConverter, PropertyMapping, SkipPropertyValue]` as a default. Now if someone decides that he would rather use .None then he could change that by calling:
`ConversionOptions.DefaultComparing = [.None]`
The standard default will work in your case.

This has now been pushed as version 2.33.3 to GitHub and CocaoPods

**Comment by vronin** [comment]
Thanks a lot. This worked well
