### ISSUE TITLE
Symbol not found

### ISSUE THREAD

**Issue by boardmain** [evermeer/EVReflection#98]
after upgrading (via cocoapod)
to version Installing EVReflection 2.36.0 (was 2.33.3)

i have this error when i try do run on device

```
dyld: Symbol not found: __TFC12EVReflection8EVObject11mapObjectTouRxCSo8NSObjectrfT_x
  Referenced from: /var/containers/Bundle/Application/3275DF6F-734C-4571-9C2F-72545D273D3A/liveauction.app/liveauction
  Expected in: /private/var/containers/Bundle/Application/3275DF6F-734C-4571-9C2F-72545D273D3A/liveauction.app/Frameworks/EVReflection.framework/EVReflection
 in /var/containers/Bundle/Application/3275DF6F-734C-4571-9C2F-72545D273D3A/liveauction.app/liveauction
```

what i can try? i see the framework is linked correctly

**Comment by evermeer** [comment]
The function mapObjectTo still exists in the EVObject. As you can see above that is the one that can not be found. dyld errors are caused by a missing or a bad library linking, not code. There are a couple of options that you could try:
-  do a clean (Shift, Command K)
- Remove all your pod specifications from your pod file, do a pod update to remove them from your project, then do a pod install to reinstall them
- double check your frameworks links, do not hesitate to delete/recreate the links.
  Please let me know if one of these did work for you.
